

export const playList =[
    {
      namex: 'Sevda Çiçeği',
      groupx: 'Mor ve Ötesi',
      coverx: require('./images/cover/sevdacicegi.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=b8lrQmShfy4',
      likeEvnt: false,
    },
    {
      namex: 'Teenagers',
      groupx: 'My Chemical Romance',
      coverx: require('./images/cover/teenagers.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: "https://www.youtube.com/watch?v=k6EQAOmJrbw",
      likeEvnt: false,
    },
    {
      namex: 'Arabella',
      groupx: 'Arctic Monkeys',
      coverx: require('./images/cover/arabella.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=Nj8r3qmOoZ8',
      likeEvnt: false,
    },
    {
      namex: 'Bleed It Out',
      groupx: 'Linkin Park',
      coverx: require('./images/cover/bleeditout.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=OnuuYcqhzCE',
      likeEvnt: false,
    },
    {
      namex: 'Hayatı Yaşa',
      groupx: 'Duman',
      coverx: require('./images/cover/daglarbaglar.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=c-hAgmpkm38',
      likeEvnt: false,
    },
    {
      namex: 'Smells Like Teen Spirit',
      groupx: 'Nirvana',
      coverx: require('./images/cover/smellsliketeenspirit.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=hTWKbfoikeg',
      likeEvnt: false,
    },
    {
      namex: 'Rüyalarda Buruşmuşum',
      groupx: 'Adamlar',
      coverx: require('./images/cover/ruyalardaburusmusum.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=2xbQsV6TnQ0',
      likeEvnt: false,
    },
    {
      namex: 'Dream On',
      groupx: 'Aerosmith',
      coverx: require('./images/cover/dreamon.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=89dGC8de0CA',
      likeEvnt: false,
    },
    {
      namex: 'TNT',
      groupx: 'AC/DC',
      coverx: require('./images/cover/tnt.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=NhsK5WExrnE',
      likeEvnt: false,
    },
    {
      namex: 'Bertaraf Et',
      groupx: 'Hayko Cepkin',
      coverx: require('./images/cover/bertarafet.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=RTj7_HMCBeI',
      likeEvnt: false,
    },
    {
        namex: 'İstanbul Beyfendisi',
        groupx: 'Yaşlı Amca',
        coverx: require('./images/cover/giderdihosuma.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=W0hfVoY8WGM',
        likeEvnt: false,
    },
    {
      namex: 'Black in Black',
      groupx: 'Metallica',
      coverx: require('./images/cover/blackinblack.jpg'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=pAgnJDJN4VA',
      likeEvnt: false,
    },
    {
      namex: 'Mey',
      groupx: 'Model',
      coverx: require('./images/cover/mey.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=YRerQwKAM2A',
      likeEvnt: false,
    },
    {
      namex: 'Dünyanın Sonuna Doğmuşum',
      groupx: 'Manga',
      coverx: require('./images/cover/dsd.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=pIVG3mDL9RI',
      likeEvnt: false,
    },
    {
      namex: 'Madem',
      groupx: 'Dolu Kadehi Ters Tut',
      coverx: require('./images/cover/madem.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=Y3RXd7EasIU',
      likeEvnt: false,
    },
    {
      namex: 'Aklımı Kaçırdım',
      groupx: 'Mavi Gri',
      coverx: require('./images/cover/aklimikacirdim.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=DTZd48gFvo0',
      likeEvnt: false,
    },
    {
      namex: 'Sevsene Beni',
      groupx: 'Yedinci Ev',
      coverx: require('./images/cover/sevsenebeni.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=xjHDgtfBL5w',
      likeEvnt: false,
    },
    {
      namex: 'Neden Diye Sorma',
      groupx: 'Madrigal',
      coverx: require('./images/cover/nedendiyesorma.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=GRWusdwbqPc',
      likeEvnt: false,
    },
    {
      namex: 'Anason',
      groupx: 'Zakkum',
      coverx: require('./images/cover/anason.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=Nfr_MaidZFo',
      likeEvnt: false,
    },
    {
      namex: 'Ele Güne Karşı',
      groupx: 'MFÖ',
      coverx: require('./images/cover/elegunekarsi.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=jMBBA4-qFyM',
      likeEvnt: false,
    },
    {
      namex: 'Beni Aşka İnandır',
      groupx: 'Kolpa',
      coverx: require('./images/cover/beniaskainandir.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=xJsb1l-hiJM',
      likeEvnt: false,
    },
    {
      namex: 'Kupa Kızı ve Sinek Valesi',
      groupx: 'Teoman',
      coverx: require('./images/cover/kupakizi.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=g4aBjmVZRvw',
      likeEvnt: false,
    },
    {
        namex: 'American Idiot',
        groupx: 'Green Day',
        coverx: require('./images/cover/americanidiot.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=Ee_uujKuJMI',
        likeEvnt: false,
    },
    {
        namex: 'Monster',
        groupx: 'Skillet',
        coverx: require('./images/cover/blackinblack.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=Bn96ZZpHfLo&list=PLOFxC5fwtMg5L_UETEZgVYS8EY_va8YmO&index=2',
        likeEvnt: false,
      },
      {
        namex: 'Aşkı Harcamanın 80 Yolu',
        groupx: 'TNK',
        coverx: require('./images/cover/blackinblack.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=IXt98su2uYY',
        likeEvnt: false,
      },
      {
        namex: 'Army Of The Night',
        groupx: 'Powerwolf',
        coverx: require('./images/cover/blackinblack.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=1zN7J64IeBo',
        likeEvnt: false,
    },
    {
      namex: 'Beni Knedinden Kurtar',
      groupx: 'Perdenin Ardındakiler',
      coverx: require('./images/cover/benikk.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=FOffDLV9Byg',
      likeEvnt: false,
    },
    {
      namex: 'Kendime Yalan Söyledim',
      groupx: 'Seksendört',
      coverx: require('./images/cover/kendimeys.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=l9i-0AX5sdo',
      likeEvnt: false,
    },
    {
        namex: 'Black in Black',
        groupx: 'Imagine Dragons',
        coverx: require('./images/cover/blackinblack.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'd',
        likeEvnt: false,
    },
    {
      namex: 'Halledebilirdik',
      groupx: 'Birileri',
      coverx: require('./images/cover/halledebilirdik.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=k9PB27SWs3Y',
      likeEvnt: false,
    },
    {
      namex: 'Dull Knives',
      groupx: 'Imagine Dragons',
      coverx: require('./images/cover/dullknives.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=7mr8go10ICQ',
      likeEvnt: false,
    },
    {
      namex: 'Abraxas',
      groupx: 'Therion',
      coverx: require('./images/cover/therion.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=OQxPozI8IDA',
      likeEvnt: false,
    },
    
    {
      namex: 'Islak Islak',
      groupx: 'Barış Akarsu',
      coverx: require('./images/cover/islakislak.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=2jSMXR71d6c',
      likeEvnt: false,
    },
    {
      namex: 'Black Betty',
      groupx: 'Ram Betty',
      coverx: require('./images/cover/blackbetty.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=I_2D8Eo15wE',
      likeEvnt: false,
    },
    {
      namex: 'They Don’t Care About Us',
      groupx: 'Michael Jackson',
      coverx: require('./images/cover/mj.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=t1pqi8vjTLY',
      likeEvnt: false,
    },
    {
      namex: 'Tamirci Çırağı',
      groupx: 'Cem Karaca',
      coverx: require('./images/cover/tc.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=9KkAtcPku2k',
      likeEvnt: false,
    },
    {
      namex: 'Paint It, Black',
      groupx: 'The Rolling Stones',
      coverx: require('./images/cover/paintitblack.jpg'),
      likex: require('./images/like/like4.png'),
      dontlikex: require('./images/like/dontlike4.png'),
      urlx: 'https://www.youtube.com/watch?v=O4irXQhgMqg',
      likeEvnt: false,
    },
    {
        namex: 'Thunderstruck',
        groupx: 'AC/DC',
        coverx: require('./images/cover/thunderstruck.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=v2AC41dglnM',
        likeEvnt: false,
      },
      {
        namex: 'Black in Black',
        groupx: 'AC/DC',
        coverx: require('./images/cover/blackinblack2.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=pAgnJDJN4VA',
        likeEvnt: false,
      },
      {
        namex: 'Chop Suey',
        groupx: 'System Of A Down',
        coverx: require('./images/cover/chopsuey.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=CSvFpBOe8eY',
        likeEvnt: false,
      },
      {
        namex: 'Metalingus',
        groupx: 'Alter Bridge',
        coverx: require('./images/cover/bridge.jpg'),
        likex: require('./images/like/like4.png'),
        dontlikex: require('./images/like/dontlike4.png'),
        urlx: 'https://www.youtube.com/watch?v=N-I8ALlYxdY&list=PLlsxin1gtMtUiJ37FnCX5Cz_adxrWVObU&index=2',
        likeEvnt: false,
      },
      
  ]
  